// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    dependencies {
        classpath libs.agp.buildscript
        classpath libs.kotlin.gradle
        classpath libs.nexus.staging
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.nexus.publish) apply false
    alias(libs.plugins.detekt)
}

detekt {
    input = files(rootProject.rootDir)
    config = files("$projectDir/detekt.yml")
    allRules = true
    buildUponDefaultConfig = true

    reports {
        html.enabled = true
        xml.enabled = true
        xml.destination = file("$buildDir/reports/detekt/detekt-checkstyle.xml")
        html.destination = file("$buildDir/reports/detekt/detekt-report.html")
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

allprojects {
    group = 'com.telefonica.nestedscrollwebview'
    if (System.getProperty("SNAPSHOT_VERSION") != null) {
        version = System.getProperty("SNAPSHOT_VERSION")+"-SNAPSHOT"
    } else {
        version = System.getProperty("LIBRARY_VERSION") ?: "undefined"
    }
}
apply from: "${rootProject.projectDir}/publish_maven_central.gradle"
