name: "Tests"
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: Telefonica/android-shared-workflows/.github/workflows/preintegration.yml@3.7.0
    with:
      emulators-number: 0
      assemble-tasks: 'assembleRelease'
      check-tasks: 'check detekt'
      android-tests-tasks: ''
      artifacts-paths: |
        build/reports/detekt/detekt-report.html
      artifacts-paths-to-compress: |
        unit-tests-report=app/build/reports/tests/testReleaseUnitTest
        detekt-reports=build/reports/detekt
    secrets: inherit