name: Tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      ## Build all our Build Types at once ##
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: false
          dependencies-cache-enabled: false
          configuration-cache-enabled: false
          arguments: assembleRelease

      - name: Run checks
        if: success() || failure()
        run: ./gradlew check

      - name: Run Detekt
        if: success() || failure()
        run: ./gradlew detekt
